FROM ghcr.io/astral-sh/uv:debian

SHELL ["/bin/bash", "-c"]
ENV PATH="/root/.local/bin:$PATH"

RUN mkdir /app
WORKDIR /app
COPY ./pyproject.toml ./uv.lock /app/
RUN uv sync

COPY ./src /app/src
COPY ./README.md ./setup.py /app/

RUN uv pip install .
